In [1]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('files/estatisticas_homicidio_regional.csv')

data = data[['Regiao', 'Mes', 'Total Crimes']]

months = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

data['Mes'] = data['Mes'].astype('category')
data['Mes'] = data['Mes'].cat.set_categories(months)

data.sort_values('Mes', inplace = True)

**Gráfico 1:** linha representando a média de variação ao longo do tempo nas cidades, e uma área que aponta o mínimo e o máximo de variação em determinado mês.

**Eixo $\textbf{x}$:** Meses

**Eixo $\textbf{y}$:** Média de variação de um mês para outro

**Formato do *Dataset*:** variação de um mês para o outro em cada uma das cidades

In [3]:
cidades = list(data['Regiao'].unique())

total_crimes_cidades = []

for cidade in cidades:
    total_crimes_cidades.append(data.query('Regiao == @cidade'))

for i in range(len(total_crimes_cidades)):
    percent_dif = []
    total_crimes = total_crimes_cidades[i]['Total Crimes'].to_list()

    for j in range(len(total_crimes)):
        if j == 0:
            percent_dif.append((total_crimes[j] - total_crimes[len(total_crimes) - 1]) / total_crimes[len(total_crimes) - 1] * 100)

        else:
            percent_dif.append((total_crimes[j] - total_crimes[j - 1]) / total_crimes[j - 1] * 100)
    
    total_crimes_cidades[i]['Dif Percentual'] = percent_dif

dataset1 = pd.concat(total_crimes_cidades)

dataset1

                 Regiao  Mes  Total Crimes  Dif Percentual
0             Araçatuba  Jan         158.0       -7.058824
1             Araçatuba  Fev         139.0      -12.025316
2             Araçatuba  Mar         167.0       20.143885
3             Araçatuba  Abr         151.0       -9.580838
4             Araçatuba  Mai         116.0      -23.178808
..                  ...  ...           ...             ...
67  Presidente Prudente  Ago          96.0      -14.285714
68  Presidente Prudente  Set         108.0       12.500000
69  Presidente Prudente  Out         152.0       40.740741
70  Presidente Prudente  Nov         142.0       -6.578947
71  Presidente Prudente  Dez         136.0       -4.225352

[132 rows x 4 columns]

In [4]:
dataset1.to_csv('csv/linechart.csv', index=False)

**Gráfico 2:** barra representando a variação mensal geral, ignorando as cidades

**Eixo $\textbf{x}$:** Meses

**Eixo $\textbf{y}$:** Variação de um mês para o outro

**Formato do Dataset:** variação geral de um mês para o outro

In [5]:
dataset2 = data.groupby('Mes')['Total Crimes'].sum().reset_index(name = 'Total Crimes')

In [6]:
percent_dif = []

total_crimes = dataset2['Total Crimes'].to_list()

for i in range(len(total_crimes)):
    if i == 0:
        percent_dif.append((total_crimes[i] - total_crimes[len(total_crimes) - 1]) / total_crimes[len(total_crimes) - 1] * 100)

    else:
        percent_dif.append((total_crimes[i] - total_crimes[i - 1]) / total_crimes[i - 1] * 100)

dataset2['Dif Percentual'] = percent_dif

dataset2

    Mes  Total Crimes  Dif Percentual
0   Jan        7595.0        2.275788
1   Fev        7117.0       -6.293614
2   Mar        7727.0        8.571027
3   Abr        7480.0       -3.196583
4   Mai        7289.0       -2.553476
5   Jun        6440.0      -11.647688
6   Jul        6315.0       -1.940994
7   Ago        6550.0        3.721298
8   Set        6427.0       -1.877863
9   Out        6948.0        8.106426
10  Nov        6697.0       -3.612550
11  Dez        7426.0       10.885471

In [7]:
dataset2.to_csv('csv/barchart.csv', index = False)

In [8]:
data = {'Mes': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        'Value': [0] * 12}

dataset3 = pd.DataFrame(data)

dataset3.to_csv('csv/straightline.csv', index = False)